# Generated by Django 5.1.2 on 2024-11-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_anniversary_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_country',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_flowers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
