# Generated by Django 5.1.2 on 2024-11-15 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_userprofile_default_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['default_phone_number', 'default_postcode', 'default_town_or_city', 'default_street_address1', 'default_street_address2', 'default_county', 'anniversary_date', 'birthday_date', 'favorite_flowers']},
        ),
    ]
