# Generated by Django 5.1.2 on 2024-11-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
